### ISSUE TITLE
trouble in launching the viewer

### ISSUE THREAD

**Issue by moi1882** [Kitware/itk-vtk-image-viewer#35]
Hi,
I can't find any suitable place for users, so sorry if not ok to post here.

I experience difficulties in running the viewer:
- install npm: ok
- install itk-vtk-image-viewer: ok
- listing of files (located in my D:/Dev/itkData) : ok
- launching the viewer in a web browser: ok but unable to load any file
- launching the viewer file with a file as argument: no

I am using firefox 'quantum' 64 bits v 58.0.
I get this message with or without arguments 'operation is insecure' at running. Here are the full details:
DOMException
code: 18
columnNumber: 0
data: null
filename: "http://192.168.1.200:3000/?fileToLoad=/data/CT_C.nrrd&use2D"
lineNumber: 28
message: "The operation is insecure."
name: "SecurityError"
result: 2152923154
stack: "@http://192.168.1.200:3000/?fileToLoad=/data/CT_C.nrrd&use2D:28:11\n"
__proto__: DOMExceptionPrototype { name: Getter, message: Getter, INDEX_SIZE_ERR: 1, … }

Testing the online app, I as well get an error message:
failed to compile wasm module: LinkError: import object field '_pthread_mutexattr_settype' is not a Function
itkNrrdImageIOJSBindingWasm.js:1:3721
Worker caught an error: TypeError: e.ITKImageIO is not a constructor

Using internet Explorer (not compatible as far as I understand) the console gives me: 
"Worker caught an error: TypeError: The object doesn't handle the property or the method fill »"

Thanks for your help.
Laurent

Edit: This behavior is recent. I have been able to run example in the recent past (few days ago)
Edit2: works fine with Chrome when dropping a file into the viewer. Probably a security check newly implemented in Firefox then. However, I cannot load a file using this : http://192.168.1.200:3000/?fileToLoad=/data/CT_C.nrrd
console:
ServiceWorker registration failed:  DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

**Comment by thewtex** [comment]
Thanks for the detailed report, Laurent.

I was able to reproduce the `fileToLoad` bug. It worked for me in Firefox (we may be running into a cache issue).

I will improve our CI testing to ensure that both issues are addressed, then close this issue once they are  covered.

**Comment by thewtex** [comment]
The issue was address a while ago, but now we also test Firefox with #85
