### ISSUE TITLE
Update proxy link specification when updating vtk.js>= 6.2.8

### ISSUE THREAD

**Issue by thewtex** [Kitware/itk-vtk-image-viewer#55]
xref https://github.com/Kitware/pv-web-viewer/pull/13#issuecomment-365765341

**Comment by thewtex** [comment]
Since we do not have multiple View Proxies, no changes were necessary.

**Comment by agirault** [comment]
This is about syncing representations not properties. Don't you need to update a slice in 3d if you update it in 2d? same for window/level?

**Comment by thewtex** [comment]
There is only one representation in this case.
